-- Up Migration

ALTER TABLE erc721c_configs REPLICA IDENTITY FULL;
ALTER TABLE erc721c_operator_whitelists REPLICA IDENTITY FULL;
ALTER TABLE erc721c_permitted_contract_receiver_allowlists REPLICA IDENTITY FULL;
ALTER TABLE erc721c_v2_configs REPLICA IDENTITY FULL;
ALTER TABLE erc721c_v2_lists REPLICA IDENTITY FULL;
ALTER TABLE erc721c_v3_configs REPLICA IDENTITY FULL;
ALTER TABLE erc721c_v3_lists REPLICA IDENTITY FULL;

-- Down Migration

ALTER TABLE erc721c_configs REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_operator_whitelists REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_permitted_contract_receiver_allowlists REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_v2_configs REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_v2_lists REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_v3_configs REPLICA IDENTITY DEFAULT;
ALTER TABLE erc721c_v3_lists REPLICA IDENTITY DEFAULT;
